ARG PACKAGE_NAME="latin-checker_1.0_amd64.deb"

FROM ubuntu:latest
ARG PACKAGE_NAME
WORKDIR /tmp
RUN apt-get update
RUN apt-get install -y dpkg-dev
COPY $PACKAGE_NAME /tmp/
COPY cicd/minikube/latin-checker-service.sh /tmp/
RUN dpkg -i /tmp/$PACKAGE_NAME
RUN apt-get -f install -y
RUN chmod +x /usr/bin/latin-checker

CMD ["/tmp/latin-checker-service.sh"]
