name: CI-Pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make

      - name: Build program
        run: ./build.sh
        working-directory: ./cicd

      - name: Upload binary to artifact
        uses: actions/upload-artifact@v4
        with:
          name: latin-checker-binary
          path: usr/bin/latin-checker
          retention-days: 1

  Test:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make tree

      - name: Create usr/bin/ directory for binary
        run: mkdir -p usr/bin
        working-directory: .

      - name: Download binary from artifact
        uses: actions/download-artifact@v4
        with:
          name: latin-checker-binary
          path: usr/bin

      - name: Give permissions to binary
        run: chmod +x latin-checker
        working-directory: ./usr/bin

      - name: Run tests
        run: ./test.sh
        working-directory: ./cicd

  Package:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Create usr/bin directory
        run: mkdir -p usr/bin
        working-directory: .

      - name: Download binary from artifact
        uses: actions/download-artifact@v4
        with:
          name: latin-checker-binary
          path: usr/bin

      - name: Build package
        run: ./package.sh "../latin-checker_1.0_amd64.deb"
        working-directory: ./cicd

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: latin-checker-deb-package

  Deploy:
    needs: Package
    runs-on: ubuntu-latest

    steps:
      - name: Ensure docker is available
        run: docker --version

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Download deb-package
        uses: actions/download-artifact@v4
        with:
          name: latin-checker-deb-package
          path: .

      - name: Build docker image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/latin-checker:1.0.0 -f cicd/Dockerfile .
          docker tag ${{ vars.DOCKER_USERNAME }}/latin-checker:1.0.0 ${{ vars.DOCKER_USERNAME }}/latin-checker:latest

      - name: Deploy on docker container
        run: docker run ${{ vars.DOCKER_USERNAME }}/latin-checker "oh my god i cant believe this. yo i CANT believe this."

      - name: Log in DockerHub
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy on DockerHub
        run: |
          docker push -a ${{ vars.DOCKER_USERNAME }}/latin-checker
